apiVersion: v1
kind: ServiceAccount
metadata:
  name: listener-sa
  namespace: default
  annotations:
    azure.workload.identity/client-id: "{{ .Env.workloadIdentityClientId }}"
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: listener
  namespace: default
  labels:
    app: listener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listener
  template:
    metadata:
      labels:
        app: listener
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: listener-sa
      containers:
        - name: listener
          image: "{{ .Env.SERVICE_LISTENER_IMAGE_NAME }}"
          env:
            - name: EVENT_HUB_NAMESPACE
              value: "{{ .Env.eventHubNamespace }}"
            - name: EVENT_HUB_NAME
              value: "messages"
            - name: CONSUMER_GROUP
              value: "listener"
            - name: WEB_PUBSUB_ENDPOINT
              value: "https://{{ .Env.webPubSubHostName }}"
            - name: WEB_PUBSUB_HUB
              value: "demo"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
