apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-sa
  annotations:
    azure.workload.identity/client-id: "{{.Env.WORKLOAD_IDENTITY_CLIENT_ID}}"
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: api-sa
      containers:
        - name: api
          image: {{.Env.SERVICE_API_IMAGE_NAME}}
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: EVENT_HUB_NAMESPACE
              value: "{{.Env.EVENT_HUB_NAMESPACE}}"
            - name: EVENT_HUB_NAME
              value: "messages"
            - name: WEB_PUBSUB_ENDPOINT
              value: "https://{{.Env.WEB_PUBSUB_HOSTNAME}}"
            - name: WEB_PUBSUB_HUB
              value: "demo"
            - name: APPLICATIONINSIGHTS_CONNECTION_STRING
              value: "{{.Env.APPLICATIONINSIGHTS_CONNECTION_STRING}}"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
